const chatBox = document.getElementById("chat-box");
const chatForm = document.getElementById("chat-form");
const chatInput = document.getElementById("chat-input");
const x = "Mental health and wellness";

function createChat(sender, message) {
  const chatBubble = document.createElement("div");
  chatBubble.classList.add("chat-bubble");
  chatBubble.classList.add(sender);
  chatBubble.textContent = message;

  chatBox.appendChild(chatBubble);
  chatBox.scrollTop = chatBox.scrollHeight;
}

function botReply(message) {
  const replies = {
    "hi": "Hello there! How can I assist you?",
    "hello": "Hello! How can I help you today?",
    "bye": "Goodbye! Have a great day!",
    "help": "Sure, I'm here to help. What do you need assistance with?",
	"how are you doing": "I'm fine.How can i help you today?",
	"ask": "Yes, what would you like to ask?",
    "bye": "See you later!",
	"how are you": "As a ChatBot i do not have feelings. I am trained to answers mental health and wellness issues ",
	"joke": "Why do programmers like bugs? Because light attracts bugs!",
	"joke":"When ladies walk, their chests becomes scattered but manchested united. I hope you get the joke",
	"who are you":"My name is Thrive, a chatbot made by Sam to assist you with issues regarding your mental health and wellness. Please note that I have huge limitations compared to ChatGPT, and I can help you only on " + x + " related questions or queries.",
	"can you assist me":"Sure, i dont't mind. Ask me i will help try and help you based on my capabilities",
	"can you help me":"Sure, i dont't mind. Ask me i will help try and help you based on my capabilities",
	"depression": "Depression is a group of conditions associated with the elevation or lowering of a person's mood such as depression or bipolar disorder  People with depression usually have the following psychological symptoms   :poor concentration <br>:feelings of excessive guilt or low self-worth<br>:hopelessness about the future <br>:thoughts about dying or suicide <br>:disrupted sleep <br> :feeling tired always and having low energy levels<br>:changes in appetite or weight<br> :feeling irritable and intolerant of others <br>:not getting any enjoyment out of life <br>:continuous low mood or sadness<br> and finding it difficult to make decisions amongst many others. The physical symptoms of depression include <br> :moving or speaking more slowly than usual <br> :changes in appetite or weight (usually decreased, but sometimes increased)<br>:unexplained aches and pains <br>:low sex drive (loss of libido) <br> :disturbed sleep – for example, finding it difficult to fall asleep at night or waking up very early in the morning <br> The social syptoms of depression  include  <br>:avoiding contact with friends and taking part in fewer social activities <br> : neglecting your hobbies and interests<br>: and having difficulties in your home, work or family life. If you have a lot of the mentioned symptoms,It is likely that you have depression.This can be caused by alot of factors including trauma<br>:loss of a loved one or family member <br> physicall ilness and financial problem amongst other <br> I suggest you try the following to help you with depression  <br>1 Meditation  :Meditation can be a helpful practice for coping with depression. It involves training your attention and awareness to achieve a mentally clear and emotionally calm state. <br> 2 Engage in self-care activities: Prioritize self-care by engaging in activities that bring you joy and relaxation. This could include hobbies, exercise, reading, spending time in nature, or practicing mindfulness and meditation. <br>  3 ,Take care of your physical health: Remember to take care of your body by eating a balanced diet, getting regular exercise, and ensuring you're getting enough sleep. Physical health can have a significant impact on mental well-being. <br> 4  Face your fears. Do not avoid things you find difficult When people feel low , they avoid talking to other people. Some people loose their confidence going out driving or travelling. If this happens to you, i suggest you face them .  " ,
	"anxiety": " Anxiety can be normal in stressful situations such as public speaking or taking a test. Anxiety is only an indicator of underlying disease when feelings become excessive, all-consuming and interfere with daily living.You may also experience physical signs of anxiety, such as a pounding heart and sweating. It’s normal to have some anxiety. People who are at risk include <br>: people who have certain personality traits such as shyness <br>: people who experienced trauma during childhood,family history of anxiety and mental heal related questions and certain health problems such as thyroid problems. On average women are prone to anxiety in  contrast to men. There are several types of anxiety disoders. <br> They include Phobias,Panic disoders and Generalized anxiety disoders. Anxiety disoders can be attributed to <br> Chemical imbalance <br> : Environmental factors and <br> : Heredity. They physical symptoms of axiety include <br>: Cold or sweaty hands <br> :Dry mouth <br> :Nausea <br> : Muscle tention and shortness of breath  <br> The mental and behaivioural symptoms include but not limited to <br>:Nightmares <br> : Trouble sleeping <br> :obssesive thoughts <br> : panicking <br> : Inability to be still and calm and Repeated thoughts or flashbacks of traumatic experiences. i suggest you do the following to cope or deal with anxiety <br>  Join support groups  <br>: Limit or avoid caffeine <br> : Go to aprofessional psychologist  . Anxiety can be prevented by <br>: Living a health lifestyle <br>:Limiting your caffeine intake and <br> : Having or being close with agroup of family and frieds who will likely be able to take notice of your mentall state",
	"stress": "Stress, either physiological, biological or psychological, is an organism's response to a stressor such as an environmental condition. Stress is the body's method of reacting to a condition such as a threat, challenge or physical and psychological barrier.  Stress affects both the mind and the body. A little bit of stress is good and can help us perform daily activities. Too much stress can cause physical and mental health problems. Learning how to cope with stress can help us feel less overwhelmed and support our mental and physical well-being. Everyone reacts differently to stressful situations. Coping styles and symptoms of stress vary from person to person. ​​  It is natural to feel stressed in challenging situations such as job interviews, school exams, unrealistic workloads, an insecure job, or conflict with family, friends or colleagues. For many people stress reduces over time as the situation improves or as they learn to cope emotionally with the situation. Stress tends to be widespread during events such as major economic crises, disease outbreaks, natural disasters, war, and community violence.   Most of us manage stress well and continue to function. If we have difficulties coping with stress, we should seek help from a trusted health-care provider or from another trusted person in our community.   Sress can be managed by <br>: Learning stress managhement <br>:    Most of us manage stress well and continue to function. If we have difficulties coping with stress, we should seek help from a trusted health-care provider or from another trusted person in our community.  <br>  <b> Keeping a daily routine  <br>:Having a daily schedule can help us use our time efficiently and feel more in control. Set time for regular meals, time with family members, exercise, daily chores and other recreational activities. <br>: <b> Get plenty of sleep <br> :Getting enough sleep is important for both body and mind. Sleep repairs, relaxes and rejuvenates our body and can help reverse the effect of stress.  <br>  :Be consistent. Go to bed at the same time each night and get up at the same time each morning, including on the weekends.   <br> : <b> Connect with others <br>  <b> Eat health </b> and <br> : <b> Exercise Daily</>  "  ,
	"motherfucker":"SORRY, I cannot answer that",
	"bloody":"SORRY, I cannot answer that",
	 "suicide": "Suicide is the act of intentionally causing one's own death. Typically, it refers to one's act of causing their own death. Mental disorders, physical disorders, and substance abuse are risk factors. Some suicides are impulsive acts due to stress, relationship problems, or harassment and bullying. People commit suicide  for a number of reasons  they include <br> :Experiencing a major life transition, such as the loss of a loved one, breaking up with a boyfriend/girlfriend, moving to a new place, or failing an exam or course, may cause someone to feel unloved, depressed, isolated and lonely.  <br> :Feelings of hopelessness and helplessness. Problems seem too much and no matter what is done, nothing appears to be getting better and no one seems to care or help. <br>  : Developing negative feelings about oneself. Someone who is suicidal may experience feelings of worthlessness and of being a failure. He or she may experience academic and or social problems at university. <br> :Wanting to end unbearable emotional pain or problems that are too overwhelming. <br> :Alcohol and substance abuse can cause someone to lose self-control and engage in impulsive suicidal behaviours. <br>   Depression is the leading cause of suicide. Depression can affect thinking so that it becomes hard to think of other ways out of a situation. People feel hopeless, helpless and see no reason to live.   <br>  :Unresolved anger. Sometimes suicide may be linked to unexpressed anger. For some people it is hard to acknowledge their anger.  <b>:Warning signs of suicide<b> <br>  :Talking or joking about suicide. Talking about dying, suicide or saying things like “Nothing matters”, “I wish I was dead” or “I won’t be around for long”. <br> :Depression. Feeling hopeless, losing interest in doing anything, and withdrawing from family and friends. <br> :  Self-criticism. Saying things like “I can do anything right” and “I am pathetic and useless”. <br>  <b> I suggest to to the following if you are suicidal </b>  <br> : Establish a support system,it could be friends or family <br> :Believe in a Better Tomorrow <br> : When you are feeling hopeless, it can be hard to picture how things could possibly get better. <br>  :  <b> Avoid Alcohol and Drugs </b> , <br>  :While it may be tempting to hide from emotional pain by using drugs or alcohol, this is actually a bad idea. These substances can intensify your feelings of sadness and hopelessness and make your situation worse. ",
     "suicidal": "Suicide is the act of intentionally causing one's own death. Typically, it refers to one's act of causing their own death. Mental disorders, physical disorders, and substance abuse are risk factors. Some suicides are impulsive acts due to stress, relationship problems, or harassment and bullying. People commit suicide  for a number of reasons  they include <br> :Experiencing a major life transition, such as the loss of a loved one, breaking up with a boyfriend/girlfriend, moving to a new place, or failing an exam or course, may cause someone to feel unloved, depressed, isolated and lonely.  <br> :Feelings of hopelessness and helplessness. Problems seem too much and no matter what is done, nothing appears to be getting better and no one seems to care or help. <br>  : Developing negative feelings about oneself. Someone who is suicidal may experience feelings of worthlessness and of being a failure. He or she may experience academic and or social problems at university. <br> :Wanting to end unbearable emotional pain or problems that are too overwhelming. <br> :Alcohol and substance abuse can cause someone to lose self-control and engage in impulsive suicidal behaviours. <br>   Depression is the leading cause of suicide. Depression can affect thinking so that it becomes hard to think of other ways out of a situation. People feel hopeless, helpless and see no reason to live.   <br>  :Unresolved anger. Sometimes suicide may be linked to unexpressed anger. For some people it is hard to acknowledge their anger.  <b>:Warning signs of suicide<b> <br>  :Talking or joking about suicide. Talking about dying, suicide or saying things like “Nothing matters”, “I wish I was dead” or “I won’t be around for long”. <br> :Depression. Feeling hopeless, losing interest in doing anything, and withdrawing from family and friends. <br> :  Self-criticism. Saying things like “I can do anything right” and “I am pathetic and useless”. <br>  <b> I suggest to to the following if you are suicidal </b>  <br> : Establish a support system,it could be friends or family <br> :Believe in a Better Tomorrow <br> : When you are feeling hopeless, it can be hard to picture how things could possibly get better. <br>  :  <b> Avoid Alcohol and Drugs </b> , <br>  :While it may be tempting to hide from emotional pain by using drugs or alcohol, this is actually a bad idea. These substances can intensify your feelings of sadness and hopelessness and make your situation worse.",
	 "depressent": "Depression is a group of conditions associated with the elevation or lowering of a person's mood such as depression or bipolar disorder  People with depression usually have the following psychological symptoms   :poor concentration <br>:feelings of excessive guilt or low self-worth<br>:hopelessness about the future <br>:thoughts about dying or suicide <br>:disrupted sleep <br> :feeling tired always and having low energy levels<br>:changes in appetite or weight<br> :feeling irritable and intolerant of others <br>:not getting any enjoyment out of life <br>:continuous low mood or sadness<br> and finding it difficult to make decisions amongst many others. The physical symptoms of depression include <br> :moving or speaking more slowly than usual <br> :changes in appetite or weight (usually decreased, but sometimes increased)<br>:unexplained aches and pains <br>:low sex drive (loss of libido) <br> :disturbed sleep – for example, finding it difficult to fall asleep at night or waking up very early in the morning <br> The social syptoms of depression  include  <br>:avoiding contact with friends and taking part in fewer social activities <br> : neglecting your hobbies and interests<br>: and having difficulties in your home, work or family life. If you have a lot of the mentioned symptoms,It is likely that you have depression.This can be caused by alot of factors including trauma<br>:loss of a loved one or family member <br> physicall ilness and financial problem amongst other <br> I suggest you try the following to help you with depression  <br>1 Meditation  :Meditation can be a helpful practice for coping with depression. It involves training your attention and awareness to achieve a mentally clear and emotionally calm state. <br> 2 Engage in self-care activities: Prioritize self-care by engaging in activities that bring you joy and relaxation. This could include hobbies, exercise, reading, spending time in nature, or practicing mindfulness and meditation. <br>  3 ,Take care of your physical health: Remember to take care of your body by eating a balanced diet, getting regular exercise, and ensuring you're getting enough sleep. Physical health can have a significant impact on mental well-being. <br> 4  Face your fears. Do not avoid things you find difficult When people feel low , they avoid talking to other people. Some people loose their confidence going out driving or travelling. If this happens to you, i suggest you face them .",
	"depressing":"Depression is a group of conditions associated with the elevation or lowering of a person's mood such as depression or bipolar disorder  People with depression usually have the following psychological symptoms   :poor concentration <br>:feelings of excessive guilt or low self-worth<br>:hopelessness about the future <br>:thoughts about dying or suicide <br>:disrupted sleep <br> :feeling tired always and having low energy levels<br>:changes in appetite or weight<br> :feeling irritable and intolerant of others <br>:not getting any enjoyment out of life <br>:continuous low mood or sadness<br> and finding it difficult to make decisions amongst many others. The physical symptoms of depression include <br> :moving or speaking more slowly than usual <br> :changes in appetite or weight (usually decreased, but sometimes increased)<br>:unexplained aches and pains <br>:low sex drive (loss of libido) <br> :disturbed sleep – for example, finding it difficult to fall asleep at night or waking up very early in the morning <br> The social syptoms of depression  include  <br>:avoiding contact with friends and taking part in fewer social activities <br> : neglecting your hobbies and interests<br>: and having difficulties in your home, work or family life. If you have a lot of the mentioned symptoms,It is likely that you have depression.This can be caused by alot of factors including trauma<br>:loss of a loved one or family member <br> physicall ilness and financial problem amongst other <br> I suggest you try the following to help you with depression  <br>1 Meditation  :Meditation can be a helpful practice for coping with depression. It involves training your attention and awareness to achieve a mentally clear and emotionally calm state. <br> 2 Engage in self-care activities: Prioritize self-care by engaging in activities that bring you joy and relaxation. This could include hobbies, exercise, reading, spending time in nature, or practicing mindfulness and meditation. <br>  3 ,Take care of your physical health: Remember to take care of your body by eating a balanced diet, getting regular exercise, and ensuring you're getting enough sleep. Physical health can have a significant impact on mental well-being. <br> 4  Face your fears. Do not avoid things you find difficult When people feel low , they avoid talking to other people. Some people loose their confidence going out driving or travelling. If this happens to you, i suggest you face them .",
     "trauma":"Psychological trauma is an emotional response caused by severe distressing events such as accidents, violence, rape, or sensory overload. Short-term reactions such as psychological shock and psychological denial are typically followed  Emotional and psychological trauma is the result of extraordinarily stressful events that shatter your sense of security, making you feel helpless in a dangerous world. Psychological trauma can leave you struggling with upsetting emotions, memories, and anxiety that won’t go away. It can also leave you feeling numb, disconnected, and unable to trust other people. <br> Traumatic experiences often involve a threat to life or safety, but any situation that leaves you feeling overwhelmed and isolated can result in trauma, even if it doesn’t involve physical harm. It’s not the objective circumstances that determine whether an event is traumatic, but your subjective emotional experience of the event. The more frightened and helpless you feel, the more likely you are to be traumatized. <br> :  <b> Emotional and psychological trauma can be caused by <b/>: <br> One-time events, such as an accident, injury, or a violent attack, especially if it was unexpected or happened in childhood. <br> :Ongoing, relentless stress, such as living in a crime-ridden neighborhood, battling a life-threatening illness or experiencing traumatic events that occur repeatedly, such as bullying, domestic violence, or childhood neglect and. <br>  :Commonly overlooked causes, such as surgery (especially in the first 3 years of life), the sudden death of someone close, the breakup of a significant relationship, or a humiliating or deeply disappointing experience, especially if someone was deliberately cruel. Symptoms of trauma include  <br>  Shock, denial, or disbelief. <br> :Confusion, difficulty concentrating. <br> :Anger, irritability, mood swings.I suggest you do the following to heal from trauma <br> :Try to exercise for 30 minutes or more on most days. Or if it's easier, three 10-minute spurts of exercise per day are just as good. <br>  Add a mindfulness element. Instead of focusing on your thoughts or distracting yourself while you exercise, really focus on your body and how it feels as you move. Notice the sensation of your feet hitting the ground, for example, or the rhythm of your breathing, or the feeling of wind on your skin. Rock climbing, boxing, weight training, or martial arts can make this easier—after all. ",
	 "traumatic":"Psychological trauma is an emotional response caused by severe distressing events such as accidents, violence, rape, or sensory overload. Short-term reactions such as psychological shock and psychological denial are typically followed  Emotional and psychological trauma is the result of extraordinarily stressful events that shatter your sense of security, making you feel helpless in a dangerous world. Psychological trauma can leave you struggling with upsetting emotions, memories, and anxiety that won’t go away. It can also leave you feeling numb, disconnected, and unable to trust other people. <br> Traumatic experiences often involve a threat to life or safety, but any situation that leaves you feeling overwhelmed and isolated can result in trauma, even if it doesn’t involve physical harm. It’s not the objective circumstances that determine whether an event is traumatic, but your subjective emotional experience of the event. The more frightened and helpless you feel, the more likely you are to be traumatized. <br> :  <b> Emotional and psychological trauma can be caused by <b/>: <br> One-time events, such as an accident, injury, or a violent attack, especially if it was unexpected or happened in childhood. <br> :Ongoing, relentless stress, such as living in a crime-ridden neighborhood, battling a life-threatening illness or experiencing traumatic events that occur repeatedly, such as bullying, domestic violence, or childhood neglect and. <br>  :Commonly overlooked causes, such as surgery (especially in the first 3 years of life), the sudden death of someone close, the breakup of a significant relationship, or a humiliating or deeply disappointing experience, especially if someone was deliberately cruel. Symptoms of trauma include  <br>  Shock, denial, or disbelief. <br> :Confusion, difficulty concentrating. <br> :Anger, irritability, mood swings.I suggest you do the following to heal from trauma <br> :Try to exercise for 30 minutes or more on most days. Or if it's easier, three 10-minute spurts of exercise per day are just as good. <br>  Add a mindfulness element. Instead of focusing on your thoughts or distracting yourself while you exercise, really focus on your body and how it feels as you move. Notice the sensation of your feet hitting the ground, for example, or the rhythm of your breathing, or the feeling of wind on your skin. Rock climbing, boxing, weight training, or martial arts can make this easier—after all.",
	 "traumatised":"Psychological trauma is an emotional response caused by severe distressing events such as accidents, violence, rape, or sensory overload. Short-term reactions such as psychological shock and psychological denial are typically followed  Emotional and psychological trauma is the result of extraordinarily stressful events that shatter your sense of security, making you feel helpless in a dangerous world. Psychological trauma can leave you struggling with upsetting emotions, memories, and anxiety that won’t go away. It can also leave you feeling numb, disconnected, and unable to trust other people. <br> Traumatic experiences often involve a threat to life or safety, but any situation that leaves you feeling overwhelmed and isolated can result in trauma, even if it doesn’t involve physical harm. It’s not the objective circumstances that determine whether an event is traumatic, but your subjective emotional experience of the event. The more frightened and helpless you feel, the more likely you are to be traumatized. <br> :  <b> Emotional and psychological trauma can be caused by <b/>: <br> One-time events, such as an accident, injury, or a violent attack, especially if it was unexpected or happened in childhood. <br> :Ongoing, relentless stress, such as living in a crime-ridden neighborhood, battling a life-threatening illness or experiencing traumatic events that occur repeatedly, such as bullying, domestic violence, or childhood neglect and. <br>  :Commonly overlooked causes, such as surgery (especially in the first 3 years of life), the sudden death of someone close, the breakup of a significant relationship, or a humiliating or deeply disappointing experience, especially if someone was deliberately cruel. Symptoms of trauma include  <br>  Shock, denial, or disbelief. <br> :Confusion, difficulty concentrating. <br> :Anger, irritability, mood swings.I suggest you do the following to heal from trauma <br> :Try to exercise for 30 minutes or more on most days. Or if it's easier, three 10-minute spurts of exercise per day are just as good. <br>  Add a mindfulness element. Instead of focusing on your thoughts or distracting yourself while you exercise, really focus on your body and how it feels as you move. Notice the sensation of your feet hitting the ground, for example, or the rhythm of your breathing, or the feeling of wind on your skin. Rock climbing, boxing, weight training, or martial arts can make this easier—after all.",
	 "traumatized":"Psychological trauma is an emotional response caused by severe distressing events such as accidents, violence, rape, or sensory overload. Short-term reactions such as psychological shock and psychological denial are typically followed  Emotional and psychological trauma is the result of extraordinarily stressful events that shatter your sense of security, making you feel helpless in a dangerous world. Psychological trauma can leave you struggling with upsetting emotions, memories, and anxiety that won’t go away. It can also leave you feeling numb, disconnected, and unable to trust other people. <br> Traumatic experiences often involve a threat to life or safety, but any situation that leaves you feeling overwhelmed and isolated can result in trauma, even if it doesn’t involve physical harm. It’s not the objective circumstances that determine whether an event is traumatic, but your subjective emotional experience of the event. The more frightened and helpless you feel, the more likely you are to be traumatized. <br> :  <b> Emotional and psychological trauma can be caused by <b/>: <br> One-time events, such as an accident, injury, or a violent attack, especially if it was unexpected or happened in childhood. <br> :Ongoing, relentless stress, such as living in a crime-ridden neighborhood, battling a life-threatening illness or experiencing traumatic events that occur repeatedly, such as bullying, domestic violence, or childhood neglect and. <br>  :Commonly overlooked causes, such as surgery (especially in the first 3 years of life), the sudden death of someone close, the breakup of a significant relationship, or a humiliating or deeply disappointing experience, especially if someone was deliberately cruel. Symptoms of trauma include  <br>  Shock, denial, or disbelief. <br> :Confusion, difficulty concentrating. <br> :Anger, irritability, mood swings.I suggest you do the following to heal from trauma <br> :Try to exercise for 30 minutes or more on most days. Or if it's easier, three 10-minute spurts of exercise per day are just as good. <br>  Add a mindfulness element. Instead of focusing on your thoughts or distracting yourself while you exercise, really focus on your body and how it feels as you move. Notice the sensation of your feet hitting the ground, for example, or the rhythm of your breathing, or the feeling of wind on your skin. Rock climbing, boxing, weight training, or martial arts can make this easier—after all.",
	 "mentalwellness":"Mental health encompasses emotional, psychological, and social well-being, influencing cognition, perception, and behavior. It likewise determines how an individual handles stress, interpersonal relationships, and decision-making. <b> I suggest a several steps to  improve your mentall wellness and well being</b>  1 Connect with other people  <br> : Good relationships are important for your mental wellbeing.   They can help you to build a sense of belonging and self-worth, give you an opportunity to share positive experiences and provide emotional support and allow you to support others. <br>  <b> Be physically active </b> <br> :  Being active is not only great for your physical health and fitness   <br>  <b>  Evidence also shows it can also improve your mental wellbeing by:  </b>  <br> raising your self-esteem <br> :helping you to set goals or challenges and achieve them and  causing chemical changes in your brain which can help to positively change your mood  <b> Learn new skills </b> : <br> Research shows that learning new skills can also improve your mental wellbeing by: <br> :boosting self-confidence and raising self-esteem <br> :  helping you to build a sense of purpose  <br> :helping you to connect with others <p> Even if you feel like you do not have enough time, or you may not need to learn new things, there are lots of different ways to bring learning into your life. </p>     <br>: <b>Give to others<b> <br>: <p>Research suggests that acts of giving and kindness can help improve your mental wellbeing by:</p> <br> creating positive feelings and a sense of reward <br> :giving you a feeling of purpose and self-worth <br> helping you connect with other people    <br> <p>  It could be small acts of kindness towards other people, or larger ones like volunteering in your local community.",
	 "welness": "Mental health encompasses emotional, psychological, and social well-being, influencing cognition, perception, and behavior. It likewise determines how an individual handles stress, interpersonal relationships, and decision-making. <b> I suggest a several steps to  improve your mentall wellness and well being</b>  1 Connect with other people  <br> : Good relationships are important for your mental wellbeing.   They can help you to build a sense of belonging and self-worth, give you an opportunity to share positive experiences and provide emotional support and allow you to support others. <br>  <b> Be physically active </b> <br> :  Being active is not only great for your physical health and fitness   <br>  <b>  Evidence also shows it can also improve your mental wellbeing by:  </b>  <br> raising your self-esteem <br> :helping you to set goals or challenges and achieve them and  causing chemical changes in your brain which can help to positively change your mood  <b> Learn new skills </b> : <br> Research shows that learning new skills can also improve your mental wellbeing by: <br> :boosting self-confidence and raising self-esteem <br> :  helping you to build a sense of purpose  <br> :helping you to connect with others <p> Even if you feel like you do not have enough time, or you may not need to learn new things, there are lots of different ways to bring learning into your life. </p>     <br>: <b>Give to others<b> <br>: <p>Research suggests that acts of giving and kindness can help improve your mental wellbeing by:</p> <br> creating positive feelings and a sense of reward <br> :giving you a feeling of purpose and self-worth <br> helping you connect with other people    <br> <p>  It could be small acts of kindness towards other people, or larger ones like volunteering in your local community. ",
	 "wellbeing":"Mental health encompasses emotional, psychological, and social well-being, influencing cognition, perception, and behavior. It likewise determines how an individual handles stress, interpersonal relationships, and decision-making. <b> I suggest a several steps to  improve your mentall wellness and well being</b>  1 Connect with other people  <br> : Good relationships are important for your mental wellbeing.   They can help you to build a sense of belonging and self-worth, give you an opportunity to share positive experiences and provide emotional support and allow you to support others. <br>  <b> Be physically active </b> <br> :  Being active is not only great for your physical health and fitness   <br>  <b>  Evidence also shows it can also improve your mental wellbeing by:  </b>  <br> raising your self-esteem <br> :helping you to set goals or challenges and achieve them and  causing chemical changes in your brain which can help to positively change your mood  <b> Learn new skills </b> : <br> Research shows that learning new skills can also improve your mental wellbeing by: <br> :boosting self-confidence and raising self-esteem <br> :  helping you to build a sense of purpose  <br> :helping you to connect with others <p> Even if you feel like you do not have enough time, or you may not need to learn new things, there are lots of different ways to bring learning into your life. </p>     <br>: <b>Give to others<b> <br>: <p>Research suggests that acts of giving and kindness can help improve your mental wellbeing by:</p> <br> creating positive feelings and a sense of reward <br> :giving you a feeling of purpose and self-worth <br> helping you connect with other people    <br> <p>  It could be small acts of kindness towards other people, or larger ones like volunteering in your local community.",
	 "self development":"Mental health encompasses emotional, psychological, and social well-being, influencing cognition, perception, and behavior. It likewise determines how an individual handles stress, interpersonal relationships, and decision-making. <b> I suggest a several steps to  improve your mentall wellness and well being</b>  1 Connect with other people  <br> : Good relationships are important for your mental wellbeing.   They can help you to build a sense of belonging and self-worth, give you an opportunity to share positive experiences and provide emotional support and allow you to support others. <br>  <b> Be physically active </b> <br> :  Being active is not only great for your physical health and fitness   <br>  <b>  Evidence also shows it can also improve your mental wellbeing by:  </b>  <br> raising your self-esteem <br> :helping you to set goals or challenges and achieve them and  causing chemical changes in your brain which can help to positively change your mood  <b> Learn new skills </b> : <br> Research shows that learning new skills can also improve your mental wellbeing by: <br> :boosting self-confidence and raising self-esteem <br> :  helping you to build a sense of purpose  <br> :helping you to connect with others <p> Even if you feel like you do not have enough time, or you may not need to learn new things, there are lots of different ways to bring learning into your life. </p>     <br>: <b>Give to others<b> <br>: <p>Research suggests that acts of giving and kindness can help improve your mental wellbeing by:</p> <br> creating positive feelings and a sense of reward <br> :giving you a feeling of purpose and self-worth <br> helping you connect with other people    <br> <p>  It could be small acts of kindness towards other people, or larger ones like volunteering in your local community.",
	 "mentalhealth":"Mental health encompasses emotional, psychological, and social well-being, influencing cognition, perception, and behavior.",








	
  };

  const lowercaseMessage = message.toLowerCase();

  for (const key in replies) {
    if (lowercaseMessage.includes(key)) {
      createChat("bot", replies[key]);
      return;
    }
  }

  createChat("bot", "Sorry, I couldn't understand. Can you please rephrase your question?");
}

function handleForm(e) {
  e.preventDefault();
  const message = chatInput.value;
  if (message === "") {
    return;
  } else {
    createChat("user", message);
  }
  chatInput.value = "";
  setTimeout(() => botReply(message), 500);
}

chatForm.addEventListener("submit", handleForm);
